<a href="https://colab.research.google.com/github/Dhinesh-Fedor/Python---Basics/blob/main/Python_Basics_14(Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
#Pandas

import pandas as pd
import numpy as np

data_set = pd.read_csv('weight-height.csv')
print(data_set)

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [20]:
data_set.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [7]:
data_set.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [19]:
data_set.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [11]:
data_set.tail()

      Gender     Height      Weight
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

In [12]:
data_set.shape

(10000, 3)

In [24]:
#Accessing particular column

height = pd.Series(data_set['Height'])
print(height)

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64

In [17]:
#or

data_set.Height

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64

In [28]:
#or

weight = data_set['Weight']
print(weight)

0       241.893563
1       162.310473
2       212.740856
3       220.042470
4       206.349801
           ...
9995    136.777454
9996    170.867906
9997    128.475319
9998    163.852461
9999    113.649103
Name: Weight, Length: 10000, dtype: float64

In [29]:
print(len(height) ==  len(weight))

True

In [22]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  10000 non-null  object
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB

In [26]:
height.describe()

count    10000.000000
mean        66.367560
std          3.847528
min         54.263133
25%         63.505620
50%         66.318070
75%         69.174262
max         78.998742
Name: Height, dtype: float64

In [30]:
weight.describe()

count    10000.000000
mean       161.440357
std         32.108439
min         64.700127
25%        135.818051
50%        161.212928
75%        187.169525
max        269.989699
Name: Weight, dtype: float64

In [51]:
#Modifying a dataframe

data = [
    { 'name' : 'Asabeneh', 'country' : 'Finland', 'city' : 'Helsink'},
    { 'name' : 'David', 'country' : 'UK', 'city' : 'London'},
    { 'name' : 'John', 'country' : 'Sweden', 'city' : 'Stockholm'},

]

data_frame = pd.DataFrame(data)
print(data_frame)


data_frame.columns

       name  country       city
0  Asabeneh  Finland    Helsink
1     David       UK     London
2      John   Sweden  Stockholm

Index(['name', 'country', 'city'], dtype='object')

In [54]:
#Adding a new column


weight = [50,60,70]
data_frame['weight'] = weight

height = [150,160,170]
data_frame['height'] = height



data_frame

       name  country       city  weight  height
0  Asabeneh  Finland    Helsink      50     150
1     David       UK     London      60     160
2      John   Sweden  Stockholm      70     170

In [61]:
#Deleting a label from the dataframe

delete = [1,2,3]
data_frame['delete'] = delete
print(data_frame)

data_frame.drop(labels = 'delete',axis = 1)

       name  country       city  weight  height       bml  delete       bmi
0  Asabeneh  Finland    Helsink      50     150  0.002222       1  0.002222
1     David       UK     London      60     160  0.002344       2  0.002344
2      John   Sweden  Stockholm      70     170  0.002422       3  0.002422

       name  country       city  weight  height       bml       bmi
0  Asabeneh  Finland    Helsink      50     150  0.002222  0.002222
1     David       UK     London      60     160  0.002344  0.002344
2      John   Sweden  Stockholm      70     170  0.002422  0.002422

In [60]:
#Modifying column values


#Calculating bmi
def BMI():
  weight = data_frame['weight']
  height = data_frame['height']
  return weight/(height**2)

res = BMI()


#adding it to the dataframe

data_frame['bmi'] = res
data_frame

       name  country       city  weight  height       bml  delete       bmi
0  Asabeneh  Finland    Helsink      50     150  0.002222       1  0.002222
1     David       UK     London      60     160  0.002344       2  0.002344
2      John   Sweden  Stockholm      70     170  0.002422       3  0.002422

In [62]:
#Formatting dataframe columns

#round() method is used

data_frame['bmi'] = round(data_frame['bmi'],1)
data_frame

       name  country       city  weight  height       bml  delete  bmi
0  Asabeneh  Finland    Helsink      50     150  0.002222       1  0.0
1     David       UK     London      60     160  0.002344       2  0.0
2      John   Sweden  Stockholm      70     170  0.002422       3  0.0

In [65]:
#Adding 2 more columns

birth_year = [1990,1999,2000]
data_frame['birth_year'] = birth_year

current_year = pd.Series(2024,index = [0,1,2])
data_frame['current_year'] = current_year
data_frame

age = data_frame['current_year'] - data_frame['birth_year']
data_frame['age'] = age
data_frame

,name,country,city,weight,height,bml,delete,bmi,birth_year,current_year,age
0,Asabeneh,Finland,Helsink,50,150,0.002222,1,0.0,1990,2024,34
1,David,UK,London,60,160,0.002344,2,0.0,1999,2024,25
2,John,Sweden,Stockholm,70,170,0.002422,3,0.0,2000,2024,24

In [69]:
#checking datatype of a label
print(data_frame.age.dtype)


#Convertig types
data_frame.age.astype(float)

int64

0    34.0
1    25.0
2    24.0
Name: age, dtype: float64

In [74]:
#Boolean indexing
#Syntax => dataframe[condition]

data_frame[data_frame['age'] > 25]

,name,country,city,weight,height,bml,delete,bmi,birth_year,current_year,age
0,Asabeneh,Finland,Helsink,50,150,0.002222,1,0.0,1990,2024,34

In [77]:
#Exercises

ds = pd.read_csv('Car data.csv')
ds

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type,Ex-Showroom Price,RTO,Insurance,Other,Onroad Price
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol,1430000,143000.0,84367.000,14300,"16,71,667"
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol,649000,46240.0,27791.000,5485,"7,28,516"
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel,1361600,175000.0,85943.000,27532,"16,50,075"
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol,612900,42903.0,35311.000,0,"6,91,114"
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol,1099900,116863.0,45300.000,11599,"12,73,662"
5,Mahindra XUV700,13.99,26.04,15.00,1999,5,49,Petrol,1399000,139900.0,83172.000,13990,"16,36,062"
6,Tata Nexon,8.00,15.80,17.44,1199,5,100,Petrol,799990,55999.0,42196.000,0,"8,98,185"
7,Maruti Brezza,8.34,14.14,17.38,1462,5,15,Petrol,834000,59210.0,33849.000,5485,"9,32,544"
8,Mahindra XUV 3XO,7.49,15.49,18.89,1197,5,25,Petrol,749000,52430.0,40320.000,0,"8,41,750"
9,Toyota Fortuner,33.43,51.44,10.00,2694,7,7,Petrol,3343000,334300.0,166175.000,33830,"38,77,305"
10,Mahindra Bolero,9.79,10.91,16.00,1493,7,3,Diesel,979400,90497.5,42150.656,300,"11,12,348"
11,Toyota Innova Crysta,19.99,26.55,20.00,2393,8,7,Diesel,1999000,249875.0,106309.000,19990,"23,75,174"
12,Maruti Ertiga,8.69,13.03,20.51,1462,7,9,Petrol,869000,61660.0,32520.000,5485,"9,68,665"
13,Land Rover Defender,97.00,285.00,9.20,1997,5,24,Petrol,9700000,970000.0,403278.000,97000,"1,11,70,278"
14,Maruti FRONX,7.51,13.04,21.79,1197,5,16,Petrol,751500,53405.0,30141.000,4500,"8,39,546"
15,Maruti Baleno,6.66,9.83,22.35,1197,5,9,Petrol,666000,47420.0,33850.000,4500,"7,51,770"
16,Land Rover Range Rover,2.36,260.00,13.16,2997,5,2,Diesel,23600000,2950000.0,939295.000,236000,"2,77,25,295"
17,Hyundai Exter,6.13,10.43,19.40,1197,5,26,Petrol,612800,50309.0,34300.000,600,"6,98,009"
18,Tata Harrier,14.99,26.44,16.80,1956,5,25,Diesel,1499000,187375.0,87028.000,14990,"17,88,393"
19,Mahindra Scorpio N,13.85,24.54,19.00,1997,7,34,Petrol,1385199,143320.0,70852.000,14151,"16,13,522"
20,Kia Seltos,10.90,20.37,17.00,1497,5,28,Petrol,1089900,108990.0,25916.000,17719,"12,42,525"

In [76]:
ds.head()

,Name,Min Price (Lakh),Max Price (Lakh),Range (kmpl),CC,Seats,Variants,Type,Ex-Showroom Price,RTO,Insurance,Other,Onroad Price
0,Mahindra Thar,11.35,17.60,15.20,1497,4,19,Petrol,1430000,143000.0,84367.0,14300,"16,71,667"
1,Maruti Swift,6.49,9.60,24.80,1197,5,11,Petrol,649000,46240.0,27791.0,5485,"7,28,516"
2,Mahindra Scorpio,13.62,17.42,22.00,2184,7,4,Diesel,1361600,175000.0,85943.0,27532,"16,50,075"
3,Tata Punch,6.13,10.20,20.09,1199,5,25,Petrol,612900,42903.0,35311.0,0,"6,91,114"
4,Hyundai Creta,11.00,20.15,17.40,1497,5,28,Petrol,1099900,116863.0,45300.0,11599,"12,73,662"